### ISSUE TITLE
Application doesn't work with django 1.9

### ISSUE THREAD

**Issue by wormer** [IlyaSemenov/django-modelsettings#3]
When using this application with django 1.9 the following exception appears:
**django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.**

Here's the reason:

> ...it isn’t possible to import models inside the root package of an application 
https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9

\__init__.py does have these imports:
```
from .models import Settings
from .proxy import settings
from .admin import add_to_admin
```

To support django 1.9 these imports should be removed from the root package.

**Comment by IlyaSemenov** [comment]
I pushed version 0.2.0 that supports Django 1.9. Due to the internals cleanup the API has changed slightly, please check the updated documentation. Also, this release drops support for Django 1.6 and earlier.
